"""Initial migration

Revision ID: bf48fbddd1c6
Revises: 
Create Date: 2025-06-24 00:05:30.912503

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf48fbddd1c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis', schema=None) as batch_op:
        batch_op.alter_column('data_file_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('analysis_type',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.create_index(batch_op.f('ix_analysis_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('data_file', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('filepath',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
        batch_op.alter_column('uploaded_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_data_file_uploaded_at'), ['uploaded_at'], unique=False)

    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.alter_column('data_file_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('model_type',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('target_column',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.create_index(batch_op.f('ix_prediction_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('username'))
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)

    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prediction_created_at'))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('target_column',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('model_type',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('data_file_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('data_file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_file_uploaded_at'))
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('uploaded_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('filepath',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
        batch_op.alter_column('filename',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)

    with op.batch_alter_table('analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_created_at'))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('analysis_type',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('data_file_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
